version: '3'


networks:
  laravel:

services:

  site:
    build:
        context: .
        dockerfile: nginx.dockerfile
    container_name: nginxhr
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - php
      - redis
      - mysql
      - mailhog
    networks: 
      - laravel

  mysql: 
    image:  mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "4306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      MYSQL_DATABASE: hrapp
      MYSQL_UER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - laravel
  php: 
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - 6379:6379
    networks:
      - laravel

  composer:
    build:
      context: .
      dockerfile: composer.dockerfile
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    user: laravel
    entrypoint: ['composer', '--ignore-platform-reqs']
    networks:
      - laravel
  
  artisan:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: artisan
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: laravel
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - laravel
  
